# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: bahmutov/npm-install@v1
    - run: npm run electron:build
      env:
        CI: true
        OSS_REGION: ${{ secrets.OSS_REGION }}
        OSS_ID: ${{ secrets.OSS_ID }}
        OSS_SECRET: ${{ secrets.OSS_SECRET }}
        OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
